stages:
  - build
  - deploy

build-push-images:
  tags:
  - docker
  - shared
  image: docker:20.10.16
  services:
  - docker:20.10.16-dind
  stage: build
  only: 
    - main
    - develop
    - prod
  script:
    - reg_name=$(echo "${CI_REGISTRY_IMAGE}/fds-website-${CI_COMMIT_REF_NAME}" | tr '[:upper:]' '[:lower:]')
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $reg_name:$CI_COMMIT_SHA -t $reg_name:latest -f ${CI_PROJECT_DIR}/Dockerfile .
    - docker push $reg_name:$CI_COMMIT_SHA
    - docker push $reg_name:latest

deploy-helm-chart:
  tags:
    - docker
    - shared
  image: dtzar/helm-kubectl
  stage: deploy
  only: 
    - develop
  script:
    - mkdir ~/.kube
    - echo "$KUBECONFIG_FILE" > /root/.kube/config
    - export KUBECONFIG="/root/.kube/config"
    - kubectl get ns
    - helm upgrade frontend ./charts/fds-frontend -f ./charts/fds-frontend/values-develop.yaml --set image.tag=$CI_COMMIT_SHA